encrypt:
  key-store:
    alias: ConfigServerEncryptionKey
    secret: ${ConfigServerEncryptionKey}
    password: ${ConfigServerEncryptionKey}
    location: ${PathConfigServerEncryptionKey}
server:
  ssl:
    key-alias: ConfigServerSslKey
    key-store-password: ${ConfigServerSslKey}
    key-store-type: PKCS12
    key-store: ${PathConfigServerSslKey}
  port: 8888
spring:
  security:
    user:
      password: ${ConfigServerAccessKey}
    cloud:
      config:
        server:
          git:
            uri: ${gitConfigUri}

